# .streamlit/config.toml
# Streamlit configuration

[theme]
primaryColor = "#1f8582"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
headless = false
runOnSave = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
